export const BRANDS = [
  'CAT',
  'Cummins',
  'Deutz',
  'John Deere',
  'Perkins',
  'Volvo',
  'Komatsu',
  'Scania',
];
export const SOURCE_URLS = {
  seltex: 'https://www.seltex.ru/catalog/',
  parts74: 'https://74parts.ru/catalog/?q=',
  imachinery: 'https://imachinery.ru/search/?q=',
  impart: 'https://impart.online/catalog/search/?q=',
  pcagroup: 'https://pcagroup.ru/search/?search=',
  camsparts: 'https://spb.camsparts.ru/katalog-cummins/?search=',
  ixora: 'https://b2b.ixora-auto.ru/',
  zipteh: 'https://zipteh.online/',
  blumaq: 'https://vip.blumaq.com/',
  solid: 'https://solid-t.ru/catalog/',
  voltag: 'https://voltag.ru/',
  dvpt: 'https://dv-pt.ru/',
  recamgr: 'https://recamgr.ru/',
  kta50: 'https://kta50.ru/catalog/',
  intertrek: 'http://intertrek.info/',
  truckdrive: 'https://truckdrive.ru/',
  truckmir: 'https://truckmir.ru/',
  istk: 'https://istk-deutz.ru/',
  mirdiesel: 'http://mirdiesel.ru/',
  shtern: 'https://штерн.com/',
};
export const BASICS = {
  empotyStrin: '',
};
export const SOURCE_WEBPAGE_KEYS = {
  seltex: 'seltex',
  parts74: 'parts74',
  imachinery: 'imachinery',
  impart: 'impart',
  zipteh: 'zipteh',
  ixora: 'ixora',
  blumaq: 'blumaq',
  solid: 'solid',
  pcagroup: 'pcagroup',
  camsparts: 'camsparts',
  voltag: 'voltag',
  dvpt: 'dvpt',
  recamgr: 'recamgr',
  kta50: 'kta50',
  intertrek: 'intertrek',
  truckdrive: 'truckdrive',
  truckmir: 'truckmir',
  istk: 'istk',
  mirdiesel: 'mirdiesel',
  shtern: 'shtern',
};
